# Generated by Django 6.0.4 on 2026-05-07 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=160)),
                ('date_found', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed'), ('returned', 'Returned')], default='unclaimed', max_length=20)),
                ('image_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_found', '-created_at'],
            },
        ),
    ]
