# Generated by Django 6.0.4 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_items', '0002_adminaccount_globaltemplate_claim_guestinquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='priority',
            field=models.CharField(
                choices=[('high', 'High'), ('low', 'Low')],
                default='high',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='claim',
            name='created_by_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['priority', '-created_at']},
        ),
    ]
